"""
Data Models for Telemetry, SIEM, Behavioral Analytics, and Experimentation
"""

from dataclasses import dataclass, field, asdict
from typing import List, Dict, Any, Optional
from datetime import datetime
import json
import uuid

@dataclass
class SecurityEvent:
    """Normalized security event ingested by the SIEM."""
    event_id: str = field(default_factory=lambda: str(uuid.uuid4()))
    timestamp: str = field(default_factory=lambda: datetime.now().isoformat())
    host: str = "WIN-LAB01"
    host_ip: str = "10.10.10.20"
    user: str = "user01"
    source_ip: str = "10.10.10.20"
    destination_ip: Optional[str] = "10.10.10.10"
    destination_port: Optional[int] = 445
    event_type: str = "authentication"  # authentication, process_creation, network_connection, privilege_elevation, discovery
    action: str = "success"             # success, failure, executed, blocked, queried
    process_name: Optional[str] = None
    command_line: Optional[str] = None
    parent_process: Optional[str] = None
    service_name: Optional[str] = None
    log_source: str = "Sysmon"          # Sysmon, SecurityEventLog, AuthLog, Auditd, Zeek, Nginx
    event_code: Optional[int] = 4624    # e.g., 4624 (Logon), 4625 (Failed Logon), 1 (Sysmon Process), 3 (Sysmon Net)
    metadata: Dict[str, Any] = field(default_factory=dict)
    is_simulation: bool = True          # Explicitly marked as lab test activity

    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> "SecurityEvent":
        return cls(**data)


@dataclass
class DetectionAlert:
    """Security alert generated by signature rules or behavioral anomaly engine."""
    alert_id: str = field(default_factory=lambda: f"ALT-{uuid.uuid4().hex[:8].upper()}")
    timestamp: str = field(default_factory=lambda: datetime.now().isoformat())
    detection_type: str = "BEHAVIORAL_ANOMALY"  # TRADITIONAL_RULE, BEHAVIORAL_ANOMALY, CORRELATION
    rule_name: str = "High Anomaly Score Deviation"
    severity: str = "HIGH"                      # LOW, MEDIUM, HIGH, CRITICAL
    host: str = "WIN-LAB01"
    user: str = "user01"
    anomaly_score: float = 0.85
    contributing_features: Dict[str, float] = field(default_factory=dict)
    description: str = ""
    evidence_events: List[str] = field(default_factory=list) # List of event_ids
    response_triggered: Optional[str] = None

    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)


@dataclass
class ResponseAction:
    """Simulated SOAR Response Action."""
    action_id: str = field(default_factory=lambda: f"RSP-{uuid.uuid4().hex[:8].upper()}")
    timestamp: str = field(default_factory=lambda: datetime.now().isoformat())
    alert_id: str = ""
    target_host: str = ""
    target_user: str = ""
    action_type: str = "SIMULATED_HOST_ISOLATION"  # SIMULATED_HOST_ISOLATION, SIMULATED_ACCOUNT_FLAG, CREATE_TICKET, SIMULATED_IP_BLOCK
    status: str = "EXECUTED_SAFE_SIMULATION"
    details: str = ""
    remediation_notes: str = ""

    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)


@dataclass
class UserBaseline:
    """Learned normal behavioral profile for a user/service account."""
    user: str
    learned_at: str = field(default_factory=lambda: datetime.now().isoformat())
    sample_count: int = 100
    avg_daily_auths: float = 5.0
    std_daily_auths: float = 1.2
    normal_hosts: List[str] = field(default_factory=list)
    normal_ports: List[int] = field(default_factory=list)
    normal_processes: List[str] = field(default_factory=list)
    active_hours: List[int] = field(default_factory=lambda: list(range(8, 18)))
    failed_login_ratio_mean: float = 0.02
    failed_login_ratio_std: float = 0.01
    is_admin: bool = False

    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)


@dataclass
class AttackChainStage:
    """Stage in the Attack Chain Visualization."""
    stage_id: str
    name: str
    status: str = "NO_TELEMETRY"  # TELEMETRY_RECEIVED (Green), PARTIAL_VISIBILITY (Yellow), NO_TELEMETRY (Red), DETECTED_AI (Blue)
    telemetry_events: int = 0
    anomaly_score: float = 0.0
    notes: str = ""


@dataclass
class ExperimentRecord:
    """Full experiment data structure as required in /data/experiments/."""
    experiment_id: str
    scenario: str
    start_time: str
    end_time: str
    hosts: List[str] = field(default_factory=list)
    users: List[str] = field(default_factory=list)
    events_generated: int = 0
    events_received: int = 0
    events_detected: int = 0
    events_missed: int = 0
    alerts: List[Dict[str, Any]] = field(default_factory=list)
    anomaly_scores: List[Dict[str, Any]] = field(default_factory=list)
    telemetry_gaps: List[Dict[str, Any]] = field(default_factory=list)
    response_actions: List[Dict[str, Any]] = field(default_factory=list)
    attack_chain: List[Dict[str, Any]] = field(default_factory=list)
    metrics: Dict[str, Any] = field(default_factory=dict)
    observations: List[str] = field(default_factory=list)
    analyst_conclusion: str = ""

    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)

    def save(self, file_path: str):
        with open(file_path, "w", encoding="utf-8") as f:
            json.dump(self.to_dict(), f, indent=2)
